### ISSUE TITLE
Preserve inline comments

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#1]
Preserve inline comments such as this:

    var = value   ; my comment

**Comment by mmikeww** [comment]
Also looks like this gets converted incorrectly:  

before  

    StringTrimLeft x, x, 1           ; leading +x -> x

after  

    x := SubStr(x, "1           ; leading +x -> x"+1)

**Comment by darkzbaron** [comment]
Wow massive effort, thank you!
