### ISSUE TITLE
Winexist function calls not properly converted

### ISSUE THREAD

**Issue by slycordinator** [mmikeww/AHK-v2-script-converter#104]
WinExist function calls are converted literally as-written; variables and strings are not changed to the format needed for V2.

I have a v1 AHK file with:
```
while WinExist(ahk_id %appid%, Completing the PDFCreator Setup Wizard) {
  ControlClick, TNewCheckListBox1, ahk_id %appid%, Completing the PDFCreator Setup Wizard
```

Result of conversion:
```
while WinExist(ahk_id %appid%, Completing the PDFCreator Setup Wizard) {
  ControlClick("TNewCheckListBox1", "ahk_id " appid, "Completing the PDFCreator Setup Wizard")
```

Expected Result:
```
while WinExist("ahk_id " appid, "Completing the PDFCreator Setup Wizard") {
  ControlClick("TNewCheckListBox1", "ahk_id " appid, "Completing the PDFCreator Setup Wizard")
```

In the above, the ControlClick call is properly converted, the string portions treated as such and the appid variable converted. But then the WinExist call is copied over identically to the V1 example.

The problem with the conversion is that in V2:
```
while WinExist(ahk_id %appid%, Completing the PDFCreator Setup Wizard) {
```
This calls WinExist with two parameters:
1) ahk_id (as a variable) with the value of appid appended to it
this won't work because ahk_id is intended to be a string
2) the concatenation of the variables Completing, the, PDFCreator, Setup, and Wizard
which again won't work because those aren't variables

**Comment by slycordinator** [comment]
I've checked that the same is reproducible with other v1 function calls that use ().

`WinActive(ahk_id %appid%, Completing the PDFCreator Setup Wizard)`
also gets converted to
`WinActive(ahk_id %appid%, Completing the PDFCreator Setup Wizard)`
when it should be
`WinActive("ahk_id" appid, "Completing the PDFCreator Setup Wizard")`

**Comment by CoffeeChaton** [comment]
I'm not the author of this project, but I want to ask, does your code work fine in v1?
Have you forgotten that in v1, the usage of Functions/Commands is completely different?
Add this Directive at your file?

```ahk
#Warn All, MsgBox
```

**Comment by mmikeww** [comment]
All of your v1 code is invalid

**Comment by slycordinator** [comment]
"All of your v1 code is invalid."

By [all] you apparently mean [the single excerpt posted]. And the line I
posted is valid.

"All v1 function calls ( those using parens() ) require strings just the
same as v2"

The v1 code excerpt uses strings. The update issue is that v1 and v2 handle
strings differently.

In v1, a bare unqoted string is treated as a string.

In v2, a bare unquoted string is treated as a reference to a variable with
the name of that string.

I guess I need to post other excerpts from the file where the conversion
was handled properly to show the difference.


They

**Comment by mmikeww** [comment]
> In v1, a bare unqoted string is treated as a string.

This is false. That's why the other guy CoffeeChaton asked if your v1 code even works, because it likely doesn't.

In v1, unquoted literal text is treated as a string for COMMANDS, not for Functions.

See
https://www.autohotkey.com/docs/v1/lib/IfWinExist.htm
vs
https://www.autohotkey.com/docs/v1/lib/WinExist.htm

> In v2, a bare unquoted string is treated as a reference to a variable with
the name of that string.

That's exactly how v1 also treats this line:

`while WinExist(ahk_id %appid%, Completing the PDFCreator Setup Wizard)`

v1 requires quotes around that function parameter just the same as v2 does

**Comment by mmikeww** [comment]
Valid v1 code, normal command syntax:

```
IfWinExist, Untitled - Notepad
   MsgBox, Notepad window exists
```

Valid v1 code, force command parameters to be expressions which require quotes:

```
IfWinExist, % "Untitled - Notepad"
   MsgBox, % "Notepad window exists"
```

Valid v1 code - normal function syntax, functions always require expressions:

```
if WinExist("Untitled - Notepad")
   MsgBox, Notepad window exists
```

Invalid v1 code:

```
if WinExist(Untitled - Notepad)
   MsgBox, this will never display accurately
```

**Comment by slycordinator** [comment]
In that case, I'm an idiot for assuming that the code I took from an old chocolatey repo (which I was trying to update) was valid.

I fail.

**Comment by mmikeww** [comment]
All good, if you find other issues, can't hurt to report. I don't work on this project actively but others do
