### ISSUE TITLE
<> operator isn't converted to !=

### ISSUE THREAD

**Issue by C-Peck** [mmikeww/AHK-v2-script-converter#105]
v1
```
a = 1
b = 2
if (a <> b) 
{
	testvar := "message"
	msgbox %testvar%
}
```
v2 Conversion Result
```
a := "1"
b := "2"
if (a <> b) 
{
	testvar := "message"
	MsgBox(testvar)
}
```
The <> operator isn't being replaced by != within the if statement expression

**Comment by dmtr99** [comment]
I added a simple StrReplace to the convertor, not that clean as it will also convert text, but at least this should solve this issue.

**Comment by mmikeww** [comment]
looks like this is supposed to be working based on this line:

https://github.com/mmikeww/AHK-v2-script-converter/blob/f0d76a608b21dfac62597096e18a5be544824bce/ConvertFuncs.ahk#L336

not sure why thats failing
