### ISSUE TITLE
Converting Class Declarations and New instances

### ISSUE THREAD

**Issue by sousvideonlow** [mmikeww/AHK-v2-script-converter#106]
In ahk 1 I have

```
class MyClass
{
    SomeFn()
    {
        
    }
}
```

After converting, the word 'class' disappears. I think we still need it.

Also `mc:=new MyClass` is not converting to `mc:=MyClass()`

**Comment by dmtr99** [comment]
Please doublecheck if 'class' disappears.
This does not seem to be the case in the latest version.
I added the removal of 'new'.
