### ISSUE TITLE
Usage instruction is outdated

### ISSUE THREAD

**Issue by vers-one** [mmikeww/AHK-v2-script-converter#108]
README.md says:
https://github.com/mmikeww/AHK-v2-script-converter/blob/d35cce9bdf94d610529145505b2a621af65a3269/README.md?plain=1#L21

but then:
[dmtr99 committed "Delete v2converter.exe" on Feb 25, 2023](https://github.com/mmikeww/AHK-v2-script-converter/commit/d35cce9bdf94d610529145505b2a621af65a3269)

**Comment by martukas** [comment]
Yeah. This is a problem. Not really clear how to use it based on these instructions.

**Comment by mmikeww** [comment]
You should be able to just run the `v2converter.ahk` file with AHK v2

That .exe file that was removed was simply an AutoHotkey.exe file that was renamed. Not sure why he decided to delete it. I will update the readme now
