### ISSUE TITLE
converting v1 to v2 FindText()

### ISSUE THREAD

**Issue by EB3942AFFE** [mmikeww/AHK-v2-script-converter#109]
v1 code :- 
if (ok:=FindText(X, Y, 0, 0, 203, 187, 0, 0, Text))

v2 code :- 
if (ok:=FindText(&X, &Y, 0, 0, 203, 187, 0, 0, Text))

**Comment by dmtr99** [comment]
FindText is not a native ahk function, we did not implemented conversion of custom functions.
an interesting idea, than you should first scan the code for byref variables, but I currently do not have plans and time to implement this.
