### ISSUE TITLE
Assignment line not translated well when using double quotes

### ISSUE THREAD

**Issue by parlevjo2** [mmikeww/AHK-v2-script-converter#111]
This v1 line

`Clipboard := "Powershell -command ""Get-CimInstance -ClassName win32_operatingsystem | Select-Object CSName, LastBootUpTime | FT -Autosize"""`
is translated to v2 line
`A_Clipboard := "Powershell -command ""Get-CimInstance -ClassName win32_operatingsystem | Select-Object CSName, LastBootUpTime | FT -Autosize"""`
Must be using escaped quote otherwise it gives an autohotkey error
`A_Clipboard := "Powershell -command `"Get-CimInstance -ClassName win32_operatingsystem | Select-Object CSName, LastBootUpTime | FT -Autosize`""`

**Comment by Banaanae** [comment]
working on this [here](https://github.com/Banaanae/AHK-v2-script-converter/tree/fix-issue-111)

**Comment by Banaanae** [comment]
So currently,
I have [this](https://regex101.com/r/RMoJ06/2) regex with matches only strings in an assignment
and this code which doesn't fully work
```ahk
      else if RegexMatch(Line, "i)^([\s]*[a-z_][a-z_0-9]*[\s]*:=\s*)(.*)", &Equation) ; Line is a variable assignment, check for ""
      { ; Replace "" with `", see #111
         Line := Equation[1]
         pos := RegExMatch(Equation[2], "`"((?:`"`")?(?:[^`"]*(?:`"`")?[^`"]*?)*?(?:`"`")?)`"", &match) ; https://regex101.com/r/RMoJ06/2
         if pos != 0
            Line .= "`"" RegExReplace(match[1], "`"`"", "```"") "`""
      }
```
So it still doesn't add in variables or other strings if multiple
