### ISSUE TITLE
#Include %variables% are incorrectly translated

### ISSUE THREAD

**Issue by Lexikos** [mmikeww/AHK-v2-script-converter#113]
#Include permits quotation marks in v2, but otherwise the syntax is unchanged.

Input (valid in both versions):
```
#Include %A_LineFile%\..
```
Incorrect output:
```
#Include A_LineFile "\.."
```

**Comment by mmikeww** [comment]
so the one place that we can still use %var% deref inside a quoted string
 (my fav feature that was removed from alpha)

**Comment by dmtr99** [comment]
I removed the conversion from the #Include lines.

**Comment by dmtr99** [comment]
@Lexikos 
Thanks for submitting issues, this helps this tool a lot
