### ISSUE TITLE
Mismatched braces are added for commented-out hotkeys

### ISSUE THREAD

**Issue by Lexikos** [mmikeww/AHK-v2-script-converter#116]
Input:
```
/*
#1::
    MsgBox This hotkey is unused.
return
*/

; Some comment related to the hotkey below.
#2::return
```
Incorrect output:
```
/*
#1::
{ ; V1toV2: Added bracket
    MsgBox This hotkey is unused.
return
*/

; Some comment related to the hotkey below.
} ; V1toV2: Added Bracket before hotkey or Hotstring
#2::return
```
I think the main issue is that "code" is converted in block comments. These are comments, and cannot be assumed to contain (valid) code (unless they begin with `/*@Ahk2Exe-Keep`).

The secondary issue is that only the close brace is inserted outside of the comment.

It would be better if the end of the subroutine was detected as the unconditional `return` (i.e. it is not nested under `if` or some other control flow statement, therefore the subroutine can't possibly continue beyond it). It would then be known that `return` itself is unnecessary, because it will be implied by `}`. The close brace could either replace `return` or be inserted below it.

**Comment by dmtr99** [comment]
I added code to skip the commented blocks.
