### ISSUE TITLE
Change REWUIRES -> REQUIRES

### ISSUE THREAD

**Issue by Banaanae** [mmikeww/AHK-v2-script-converter#122]
Located in [QuickConvertorV2.ahk](https://github.com/mmikeww/AHK-v2-script-converter/blob/master/QuickConvertorV2.ahk) and [QuickConvertorV2_scintilla.ahk](https://github.com/mmikeww/AHK-v2-script-converter/blob/master/QuickConvertorV2_scintilla.ahk)

**Comment by jvr-ks** [comment]
A typo in a comment ...

**Comment by dmtr99** [comment]
This is now corrected.
