### ISSUE TITLE
Add "#Requires AutoHotkey v2.0"

### ISSUE THREAD

**Issue by futag** [mmikeww/AHK-v2-script-converter#125]
When convert complete, add `#Requires AutoHotkey v2.0` above for not open dialog choice open AHK v1

**Comment by dmtr99** [comment]
This was done on purpose, as this convertion is used to also convert small parts of scripts.
I could however add it as an option to the Quick Convertor V2, that can be enabled and disabled.

**Comment by mmikeww** [comment]
perhaps we can do a check if a full file is submitted, only then add the line

**Comment by mmikeww** [comment]
if you like that, it seems fine
