### ISSUE TITLE
Gui New command

### ISSUE THREAD

**Issue by dmtr99** [mmikeww/AHK-v2-script-converter#127]
The "Gui, New" command should be ignored or changed to create a new Gui:

example:
Gui, New
Gui, Add, ListBox, w200 voptiontext, text1|text2|
Gui, Add, Button, Default gOK, OK
Gui, Show,
return
OK:
Gui, Submit
;KeyWait, LButton, D, L
Click, 642, 358
SendInput %optiontext%
ExitApp

**Comment by mmikeww** [comment]
its a best practice to get into referencing the PR number inside the commit message

so looks like you fixed this in commit b2cc2cac77599

in that message you could also say "Closes PR #127"

**Comment by dmtr99** [comment]
OK, I will do that in the future
Thanks for the tip
