### ISSUE TITLE
Issue in converting menu code

### ISSUE THREAD

**Issue by user1823** [mmikeww/AHK-v2-script-converter#131]
V1 code:
```ahk
Menu, Image, Add, Invert colours of image in clipboard, InvertImageInCb
Menu, Image, Add, Save Clipboard Image as File, SaveCbImageasFile
Menu, Image, Add, Save Clipboard Image as 8-bit PNG, SaveCbImageas8Bit

InvertImageInCb() {

    RunWait, magick.exe convert clipboard:myimage -channel RGB -negate -background white -flatten clipboard:, , Hide
    MsgBox, Inverted colors of image in clipboard.
}
```

Converted code:
```ahk
Image := Menu()
Image.Add("Invert colours of image in clipboard", InvertImageInCb)
Image.Add("Save Clipboard Image as File", SaveCbImageasFile)
Image.Add("Save Clipboard Image as 8-bit PNG", SaveCbImageas8Bit)

InvertImageInCb() {
    RunWait("magick.exe convert clipboard:myimage -channel RGB -negate -background white -flatten clipboard:", , "Hide")
    MsgBox("Inverted colors of image in clipboard.")
}
```

This is after correcting the incorrect replacement of the word "clipboard" (https://github.com/mmikeww/AHK-v2-script-converter/issues/115)

Also, the other two functions are also defined. I just didn't include them here to prevent clutter.

However, I am getting an "Invalid callback function" error with this converted code.

PS: The menu code and the definitions of the callback functions are separated by more than 500 lines of code in both old and new AHK files.

**Comment by Banaanae** [comment]
> This is after correcting the incorrect replacement of the word "clipboard"

This is fixed now


> However, I am getting an "Invalid callback function" error with this converted code.

This is because menu callbacks require the params `(ItemName, ItemPos, MyMenu)` (or just *), and AFAIK we don't have any code to fix up these issues yet

If anyone does tackle this there is another issue with OnMessage, where in v1 you could have any number of callback params, and now you need all 4 (or once again *)

**Comment by user1823** [comment]
> This is because menu callbacks require the params (ItemName, ItemPos, MyMenu) (or just *)

Adding * solved the issue for me. Thanks!
