### ISSUE TITLE
Menu icons not converting correctly

### ISSUE THREAD

**Issue by Jeffery02** [mmikeww/AHK-v2-script-converter#138]
`Menu, MenuName, Icon, MenuItemName, Filename.png,, 0`
became
`MenuName.Icon("MenuItemName", "Filename.png")`
instead of
`MenuName.SetIcon("MenuItemName", "Filename.png",, 0)`

**Comment by Banaanae** [comment]
Shouldn't be too hard of a fix, I'll work on it now
