### ISSUE TITLE
`#UseHook On` is rejected

### ISSUE THREAD

**Issue by Irfy** [mmikeww/AHK-v2-script-converter#142]
`#UseHook On` is valid code in v1.1, but is rejected as invalid by the converter.

`#UseHook On` should be treated the same as `#UseHook` without an argument (as per [documentation](https://www.autohotkey.com/docs/v1/lib/_UseHook.htm)).

**Comment by Irfy** [comment]
This only happens when I run v2converter.ahk though... Not sure what's up.

**Comment by mmikeww** [comment]
Interesting. There should be no differences between using v2convertor or
QuickConverter. Will have to look into it. Thanks for the report

**Comment by Banaanae** [comment]
Both scripts convert `#UseHook On` to use `#UseHook true` (valid code)

Could you share your script?
