### ISSUE TITLE
How to "run the included QuickconvectorV2.ahk"

### ISSUE THREAD

**Issue by niico100** [mmikeww/AHK-v2-script-converter#145]
Firstly there's a typo, it says 'QuickConvectorV2.ahk' instead of 'QuickConvertorV2.ahk'.

Secondly how do I run it?

It says on point 1 "Then run the included QuickConvectorV2.ahk file with AHK V2 Beta".

I've been using V1 for years and am a developer and have no idea how to run this. I installed and ran V2 and don't see a run script option.

Just a small explanation would be super helpful to non expert users.

Thanks.

**Comment by Banaanae** [comment]
Thanks, I'll fix the README soon
1) Download [AHK v2.0](https://www.autohotkey.com/download/) (It says beta but I've been using it with full release and it works fine)
2) Run `QuickConvertorV2.ahk` using AHK v2.0
3) On the left Textbox enter in your v1 script and press the green arrow
4) Run the v2 script, conversion may not be perfect so you'll need to manually fix that

**Comment by niico100** [comment]
This may sound obvious but I didn't realise you had to just double click the script to run it after installing AHK 2🤡
Please add that to the README 👍

**Comment by Banaanae** [comment]
README's been updated in #150, is it more clear now?

**Comment by Banaanae** [comment]
Closing this issue now as the changes have been made, If you feel otherwise please reopen

**Comment by niico100** [comment]
Yes looks great 👍
