### ISSUE TITLE
RegExReplace convert error

### ISSUE THREAD

**Issue by tdalon** [mmikeww/AHK-v2-script-converter#157]
The tool converts: 
`RegexReplace(sName,",.*","")`

to 

`RegexReplace(sName,",.*"""`

Missing the coma and closing )

(I run the tool from v2converter)

**Comment by Banaanae** [comment]
![image](https://github.com/mmikeww/AHK-v2-script-converter/assets/83927639/e68a546f-e75c-49f7-96cf-b52f682c55d2)
Can't replicate, are you using the latest version?
Check if this occurs with that line only or only with entire script

**Comment by Banaanae** [comment]
Replacing L339 in convert funcs with `if InStr(Line, "`"`"") and !InStr(Line, "(") {` fixes, but breaks below
```ahk
var := """" A() """"
MsgBox % var

MyFunc() {
return "Works"
}
```

**Comment by tdalon** [comment]
Ok. so you can reproduce the issue and work on it, right?
