### ISSUE TITLE
Feature request for v2converter: memorize starting directory

### ISSUE THREAD

**Issue by tdalon** [mmikeww/AHK-v2-script-converter#158]
It would be nice if the v2converter would memorize the starting directory for the file selection.

Converting a whole repo each time I need to browse to my source repo directory. This would save me a lot of time.

**Comment by tdalon** [comment]
You can hard-code the directory in the v2converter script. Is enough for my use case.

`;DefDir := A_ScriptDir
   DefDir := "C:\GitHub\PowerTools"
   FN    := ""
   FNOut := ""

   ;USE SWITCH CASE TO DEAL WITH COMMAND LINE ARGUMENTS
   switch A_Args.Length
   {
      case 0:  ;IF NO ARGUMENTS THEN LOOK UP SOURCE FILE AND USE DEFAULT OUTPUT FILE
      {
         FN := FileSelect("", DefDir , "Choose an AHK v1 file to convert to v2")`

**Comment by Banaanae** [comment]
The variables are there to make conversion easier for your use case

Maybe I should add something in the README making this more clear?

**Comment by tdalon** [comment]
The variable for the starting directory is not in the SETTINGS session of the v2converter script.
(See my last comment as example.)
It would be a good point to add + document, I think.
