### ISSUE TITLE
Loop Parse not properly converted

### ISSUE THREAD

**Issue by tdalon** [mmikeww/AHK-v2-script-converter#161]
The first , after Loop Parse shall be removed by the conversion.

See https://www.autohotkey.com/docs/v2/lib/LoopParse.htm

`Loop, Parse, list, % listDelim`

is converted to 

`Loop Parse, list, listDelim`

It shall be:

`Loop Parse list, listDelim`

**Comment by tdalon** [comment]
Added this in v2converter after the call to Convert

`outscript:= StrReplace(outscript,"Loop Parse,", "Loop Parse")`

**Comment by Banaanae** [comment]
Both `Loop Parse, list, listDelim` and `Loop Parse list, listDelim` are valid code

Is there any particular reason as to why the second one should be the output?

**Comment by Banaanae** [comment]
Infact the examples on the page you linked have commas after parse
https://www.autohotkey.com/docs/v2/lib/LoopParse.htm#Examples

**Comment by fade2gray** [comment]
It appears that in v2 syntax, the `,` after `parse` is optional, but is not indicated in the v2 documentation.

**Comment by Banaanae** [comment]
Almost seems like a v1 thing :)
I think I can close this issue now, but if you feel otherwise just reopen it

**Comment by tdalon** [comment]
I thought I got an error at run because of this missing , after Loop Parse. I will recheck and reopen the issue in case.
