### ISSUE TITLE
Help adding a hotkey to switch edit controls in QuickConvertorV2.ahk.

### ISSUE THREAD

**Issue by LAPIII** [mmikeww/AHK-v2-script-converter#168]
I think that I need to add to the `GuiTest(strV1Script:="")` function, line 588:

```
 ; Add a hotkey to switch between the panes
    #Hotif WinActive "Quick Convertor V2"
    ^Tab::
        if (V1Edit.Focused) {
            V2Edit.Focus()
        } else {
            V1Edit.Focus()
        }
    return
```

I just don't know exactly where to place it. What possibly can conflict with that is that I had created line 641 with `V1Edit.Focus()` to start with the insertion cursor in the first edit box.

EDIT: I also had the idea to switch to the second edit control after the convert button is clicked, by modifying the `ButtonConvert(*)` function with the following, but the window was opening wiith the insertion cursor in the second edit box despite using `V1Edit.Focus()`:
```
ButtonConvert(*) {
    if (CheckBoxViewSymbols.Value) {
        MenuShowSymols()
    }
    V2Edit.Text := Convert(V1Edit.Text)
    V2Edit.Focus()  ; Focus the V2Edit control after conversion
}
```

**Comment by Banaanae** [comment]
Is this what you want? Place on L1137

```ahk
#HotIf WinActive(MyGui.title)
^Tab:: {
    if (V1Edit.Focused) {
        V2Edit.Focus()
    } else {
        V1Edit.Focus()
    }
}
```

Or alternatively this code which only switches if an edit is already focused

```ahk
#HotIf WinActive(MyGui.title)
$^Tab:: {
    if (V1Edit.Focused) {
        V2Edit.Focus()
    } else if (V2Edit.Focused) {
        V1Edit.Focus()
    } else {
        Send("^{Tab}")
    }
}
```

**Comment by LAPIII** [comment]
I got the error `Hotkeys/hotstrings are not allowed inside functions or classes.` and the only changes I had made to the script are:

- Replace line 640 with `V1Edit := MyGui.Add("Edit", "x280 y0 w600 vvCodeV1 +Multi +WantTab +0x100", "")`
- Remove lines 573 - 577:
- Create line 166 with `V1Edit.Focus()`  
- Added under line 1050 `^!c::ButtonConvert()` and `^w::ExitApp`
