### ISSUE TITLE
Using "input" as a variable name leads to improper conversions.

### ISSUE THREAD

**Issue by srourbrendan** [mmikeww/AHK-v2-script-converter#177]
v1 code:

```AutoHotkey
input := Clipboard
```

Expected v2 code:

```AutoHotkey
input := A_Clipboard
```

Generated code:

```AutoHotkey
ih:= A_Clipboard := InputHook(), ih:= A_Clipboard.Start(), ih:= A_Clipboard.Wait(), := A_Clipboard := ih:= A_Clipboard.Input
```

It appears to detect the input variable as the v1 Input command, and attempt to convert it to the v2 InputHook function.

**Comment by Banaanae** [comment]
This happens with *any* variable that shares a name with a command
![image](https://github.com/mmikeww/AHK-v2-script-converter/assets/83927639/0017a98b-0001-4201-9517-f0a480341184)
