### ISSUE TITLE
Conversion of ternaries with double quotes

### ISSUE THREAD

**Issue by Banaanae** [mmikeww/AHK-v2-script-converter#197]
After similar issues were reported in #147 I did more testing

V1:
```ahk
Var2 := " ""Test"" "

Var := """Test""" = Trim(Var2) ? true : false

MsgBox % Var
```

V2 (Converted):
```ahk
Var2 := " `"Test`" "

Var := "`"Test`"" 

MsgBox(Var)
```

V2 (Expected):
```ahk
Var2 := " `"Test`" "

Var := "`"Test`"" = Trim(Var2) ? true : false

MsgBox(Var)
```

**Comment by andymbody** [comment]
Converts correctly on my end... are you using the latest script?

**Comment by andymbody** [comment]
Converts correctly on my end... silly question but... are you using the latest script?

**Comment by Banaanae** [comment]
D:
I blame this
![image](https://github.com/mmikeww/AHK-v2-script-converter/assets/83927639/dfb749b9-002e-4125-9457-008f93f7f3ad)
