### ISSUE TITLE
RegExMatch_StartingPos.ah2

### ISSUE THREAD

**Issue by andymbody** [mmikeww/AHK-v2-script-converter#203]
RegExMatch_StartingPos.ah2

V1:
```
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", Match, StartingPos)
	RegExMatch("", "", Match, 0)
	RegExMatch("", "", Match, 1-1)
}
Func1()

Func2() {
	local NotMatch, Match0, Match1, Match2, MatchAbc, NotMatch
}

```

V2 (Converted):
```
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", &Match, (StartingPos)<1 ? (StartingPos)-1 : (StartingPos))
	RegExMatch("", "", &Match, -1)
	RegExMatch("", "", &Match, (1-1)<1 ? (1-1)-1 : (1-1))
}
Func1()

Func2() {
	local NotMatch, Match0, Match1, Match2, MatchAbc, NotMatch
}

```

V2 (Expected):
```
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", &Match, (StartingPos)<1 ? (StartingPos)-1 : (StartingPos))
	RegExMatch("", "", &Match, -1)
	RegExMatch("", "", &Match, (1-1)<1 ? (1-1)-1 : (1-1))
}
Func1()

Func2() {
	local NotMatch, Match, MatchAbc, NotMatch
}

```

The converted code above is with function masking implemented, and looks correct to me. However, the expected result is what happens when function masking is NOT implemented, and looks wrong to me. The current code shows it as correct, but I disagree. Once the masking was implemented, the test shows broken, but I think the converted shown above is correct (Func2 local vars are not changed).

Am I correct or wrong?

**Comment by Banaanae** [comment]
So if I'm correct the converter is deleting variables? Doesn't seem very intended.

I'll look into it when I get home

**Comment by andymbody** [comment]
> So if I'm correct the converter is deleting variables? Doesn't seem very intended.
>

Looks like it?
