### ISSUE TITLE
RegExMatch_StartingPos.ah2

### ISSUE THREAD

**Issue by andymbody** [mmikeww/AHK-v2-script-converter#204]
V1:
```
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", Match, StartingPos)
	RegExMatch("", "", Match, 0)
	RegExMatch("", "", Match, 1-1)
}
Func1()

Func2() {
	local NotMatch, Match0, Match1, Match2, MatchAbc, NotMatch
}

```

V2 (Converted):
```
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", &Match, (StartingPos)<1 ? (StartingPos)-1 : (StartingPos))
	RegExMatch("", "", &Match, -1)
	RegExMatch("", "", &Match, (1-1)<1 ? (1-1)-1 : (1-1))
}
Func1()

Func2() {
	local NotMatch, Match0, Match1, Match2, MatchAbc, NotMatch
}

```

V2 (Expected):
```
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", &Match, (StartingPos)<1 ? (StartingPos)-1 : (StartingPos))
	RegExMatch("", "", &Match, -1)
	RegExMatch("", "", &Match, (1-1)<1 ? (1-1)-1 : (1-1))
}
Func1()

Func2() {
	local NotMatch, Match, MatchAbc, NotMatch
}

```

The converted code above is with function masking implemented, and looks correct to me. However, the expected result is what happens when function masking is NOT implemented, and looks wrong to me. The current code shows it as correct, but I disagree. Once the masking was implemented, the test shows broken, but I think the converted shown above is correct (Func2 local vars are not changed).

Func1 vars should not affect Func2 vars. And this is preserved when function masking is implemented. I'm not sure why this test case was showing as correct when the Func1 vars were causing change to func2 vars using the current converter version (without masking). 

Am I correct or wrong about this? I want to make sure before I change the expected state of this test.

**Comment by Banaanae** [comment]
Same comment as in #202

Btw, nothing wrong with editing your original issue or making a new comment

**Comment by andymbody** [comment]
> Same comment as in #203
> 
> Btw, nothing wrong with editing your original issue or making a new comment

Hmmm... it got posted twice? Still learning this site format. Much different than ahk forum.

**Comment by Banaanae** [comment]
Looks like these issues might be related to the #118 fix
Should be beneficial as below example is also broken
```ahk
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", Match, StartingPos)
	RegExMatch("", "", Match, 0)
	RegExMatch("", "", Match, 1-1)
}
Func1()

Func2() {
	local NotMatch, Match0, Match1 := "Test", Match2, MatchAbc, NotMatch
	MsgBox % Match1
}
```
```ahk
Func1() {
	local Match
	StartingPos := 0
	RegExMatch("", "", &Match, (StartingPos)<1 ? (StartingPos)-1 : (StartingPos))
	RegExMatch("", "", &Match, -1)
	RegExMatch("", "", &Match, (1-1)<1 ? (1-1)-1 : (1-1))
}
Func1()

Func2() {
	local NotMatch, Match := "Test", Match2, MatchAbc, NotMatch
	MsgBox(Match[1])
}
```

**Comment by andymbody** [comment]
Ok... so far there is only 1 legit breakage by implementing the func mask. It relates to adding * param for function calls for menu, etc. So an adjustment will need to be made to handle those after all code is converted and functions are restored. I think it will be fairly easy to do this, but I have not looked at the portion of code that handles this yet. I personally think we should test the masking first before an official PR. I'd like to have help with the testing. Would you be interested in taking it for a test run?

Classes are a little more involved since they have methods (functions) as well. Currently Classes are masked first, then functions. Once the main script functions are converted and restored, Classes are unfolded and masking of the sub-members (methods) take place, the core of the class is converted (static and obj members), then the methods are unfolded and handled individually (just like normal functions). Then the full class with all its sub-component conversions is placed back into the main code (that has already been converted). I have not implemented Classes yet (but the code is almost done), and the tests included with the converter have no classes for testing. But I do have lots of code (library of past scripts) to test it on. We can build some test files as we go.

**Comment by andymbody** [comment]
So... I wonder what would happen if we convert the main (global) part of the script last, rather than first. I wonder if the v2 code that was converted for classes and functions would cause an issue? It shouldn't theoretically,  right? I have not tested. This would illuminate the adjustment mentioned for function params ubove. I will test this next.

**Comment by andymbody** [comment]
Ok... thanks for the heads up... 

I'm still testing the proper order for conversion. I will let you know the results over the next couple days. 

Based on recent tests, I'm now thinking... convert the main (global) body last rather than first. Will test to see which has less breakage of current test files. I only have one test that failed with function masking. And rearranging the order may solve that.

**Comment by andymbody** [comment]
This will be (is) fixed with upcoming masking PR.
