### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xmaxrayx** [mmikeww/AHK-v2-script-converter#206]
Hi thanks for the project <3

 can you tell me the licenses?

**Comment by Banaanae** [comment]
It is quite common for ahk repos to exist without a license,
this would be best left up to @mmikeww

**Comment by mmikeww** [comment]
see #207 
i wanted to just use the WTFPL (http://wtfpl.net/) but since this project is large i figured we should add a no-warranty clause so i issued PR for the UNLICENSE

**Comment by Banaanae** [comment]
Added in #207

**Comment by xmaxrayx** [comment]
@banaanae Yeah true

Will thank you all for declaring the license <3
