### ISSUE TITLE
Return_ex2 test failing

### ISSUE THREAD

**Issue by andymbody** [mmikeww/AHK-v2-script-converter#209]
V1:
```
MsgBox("Return, Test")

```

V2 (Converted):
```
MsgBox("Return, Test")

```

V2 (Expected):
```
MsgBox("Return, Julio")

```

Not sure why the "expected" code has "Julio" rather than "Test", or why this test case was submitted in a recent PR ?

**Comment by Banaanae** [comment]
Mistake on my end, the save button doesn't always work :(
I'll push fix asap

**Comment by andymbody** [comment]
@Banaanae
Would you be willing to open a direct line of communication, maybe Whatsapp (I don't have any other social media)? Might be beneficial for ongoing collaboration on this project. If so, please send me a message on AHK forum to set something up. Thanks.

**Comment by Banaanae** [comment]
I don't have Whatsapp, however if want somewhere to discuss there is a discussions tab on github (just like Issues and Pulls), if you want you can ask mike to turn that on

That way other contributors can also collaborate, see [this repo for what they loook like](https://github.com/github/forgoodfirstissue/discussions)

**Comment by andymbody** [comment]
> there is a discussions tab on github

Might be helpful?

**Comment by fade2gray** [comment]
Good examples of discussions ...

https://github.com/mark-wiemer-org/ahkpp/discussions
https://github.com/dnGrep/dnGrep/discussions

**Comment by mmikeww** [comment]
Discussions tab now enabled

**Comment by andymbody** [comment]
> Discussions tab now enabled

Thank you! More tools/toys to explore...
