### ISSUE TITLE
VisualDiff errors when viewing files with LF terminators - working on this now

### ISSUE THREAD

**Issue by andymbody** [mmikeww/AHK-v2-script-converter#225]
VisualDiff generates errors when v1 source file has LF terminators rather than CRLF. I found the easiest way to remedy this is to create a temp file that contains CRLF terminators (prior to conversion), then read/process that file. This is because the code responsible for VisualDiff-reads get the data directly from disk (rather than a variable). A temp file would allow all script files to reference the same data properly formatted as CRLF. The temp file can then be deleted after conversion.

I am working on this now and will post a PR shortly.

I posted this issue in case one of you have a better solution. But I think the temp file is the easiest way to approach it. More than 6% of my library files (thousands of files from multiple sources) have this issue, and generate errors. So, this is common enough to warrant an automatic solution that prevents those errors that other users may encounter also.

**Comment by Banaanae** [comment]
> This is because the code responsible for VisualDiff-reads get the data directly from disk (rather than a variable).
So converting LF to CRLF as the file is read not work?

If temp file is the only solution make sure you add it to the `.gitignore` file (this would make the file not show up in the unstaged file list)

**Comment by andymbody** [comment]
> > This is because the code responsible for VisualDiff-reads get the data directly from disk (rather than a variable).
> > So converting LF to CRLF as the file is read not work?
> 
> If temp file is the only solution make sure you add it to the `.gitignore` file (this would make the file not show up in the unstaged file list)

The temp file only gets created on the fly (in same folder as source and convert files) when the user wants to view before/after conversion. It is immediately removed after user exits VisualDiff. Correct me if I am wrong, but this temp file should not affect the project itself, right? And therefore no edit to .gitignore should be required, correct?

**Comment by Banaanae** [comment]
> Correct me if I am wrong, but this temp file should not affect the project itself, right? And therefore no edit to .gitignore should be required, correct?

Won't affect it at all, it's just a nice addition to prevent accidental commits and show future contributors that this file is only temporary

**Comment by andymbody** [comment]
> Won't affect it at all, it's just a nice addition to prevent accidental commits and show future contributors that this file is only temporary

Ok, but I do not have a filename to reference. The filename is unique/dynamic (based on the source file name), and is only known at the time it is created. There will not be another file with this name created in the history of mankind (lol).

I will put a note in the file you mentioned but am unable to provide an actual filename. I can place an example filename there. Will that be sufficient?

**Comment by Banaanae** [comment]
> Will that be sufficient?

Yes, thanks!
