### ISSUE TITLE
Pixel(Search|GetColor)

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#23]
v2changes:

> PixelSearch and PixelGetColor use RGB values instead of BGR, for consistency with other commands.

**Comment by dmtr99** [comment]
I added at least a warning.

Another option would be to use an BGRtoRBG  and RBGtoBRG functions and add it in the bottom.
We could also just convert the numbers, but that would not be tranparant for the users...

**Comment by Banaanae** [comment]
Made some changes to this:
Search
- Remove Mode param (not used anymore)
- Convert BGR to RGB (and leaving note for user)

Still need to remove RGB param from GetColor mode
