### ISSUE TITLE
Pasting V1 code into converter sometimes gets hijacked by buildPtn_MSTR()

### ISSUE THREAD

**Issue by fade2gray** [mmikeww/AHK-v2-script-converter#248]
... and this regex gets pasted in the window instead ...

```
(*UCP)(?s)(?<var>[_a-z]\w*)\h*=(?>\s*(?:(?:(?:\h*;|(?<=\h);).*)|(?:#TAG★\w+★#))*)*\R+(?<blk>\((?<guts>(?>.+?)+?)\R+\h*\))
```

**Comment by Banaanae** [comment]
Are you running latest version? This should've been fixed here https://github.com/mmikeww/AHK-v2-script-converter/commit/95a54b795d01105c2299451eff6effd41859a069

**Comment by fade2gray** [comment]
That commit was made on July 04, I've re-synced my fork several times since then.

**Comment by fade2gray** [comment]
All OK since re-syncing.
