### ISSUE TITLE
Same line action also needs conversion

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#25]
Split from Issue #3 
Related to Issue #14 

needs to recurse somehow if the same-line action is another command that needs to be converted:

```autohotkey
IfNotEqual leftlist,, SetEnv item, `,%item%
```

this is wrong:

```autohotkey
if (leftlist != ""), SetEnv item, `,%item%
```

needs to be:

```autohotkey
if (leftlist != ""), item := "," . item
```

**Comment by mmikeww** [comment]
and what if its another IfCommand chained?

this looks like its valid v1 code:

```autohotkey
var = 3
IfEqual, var, 3, IfGreater, var, 1, IfLess, var, 5, MsgBox
```

and this works in v2:

```autohotkey
var := 3
if (var = 3), if (var > 1), if (var < 5), MsgBox
```

god damnit

**Comment by mmikeww** [comment]
may need to refactor into smaller funcs so i can recursively call them

**Comment by safetycar** [comment]
This is no longer possible in v2 `if (var = 3), if (var > 1), if (var < 5), MsgBox`

But the conversion is done with an indented line jump, so it seems that the issue can be closed.
