### ISSUE TITLE
The new release does not run

### ISSUE THREAD

**Issue by fade2gray** [mmikeww/AHK-v2-script-converter#252]
... no errors, nothing, but it runs OK if I compile it from the zip, difference in file sizes though - release is 3660 KB, compiled from zip is 1282 KB.

**Comment by Banaanae** [comment]
The binary doesn't include test suite, scintilla lib or diffing files (so smaller binary)
It worked for me, however I had to go through the window smart screen, do you have any antivirus or windows defender settings that could be blocking it? It does create 2 exe files which could cause it to be blocked

**Comment by Banaanae** [comment]
The file size difference could be due to difference in compiler settings?
https://github.com/CCCC-L/Action-Ahk2Exe/blob/main/action.yml

**Comment by Banaanae** [comment]
Compiling myself I get 3638KB
![image](https://github.com/user-attachments/assets/2033af57-94f8-4d00-b913-93d537a029bf)
![image](https://github.com/user-attachments/assets/39d7ddd2-095a-49e5-bfc2-759f7ec44d38)

**Comment by fade2gray** [comment]
> windows defender settings

Of course, had to disable `Check apps and files` in `Reputation-based protection` - it's really annoying that such events don't get flagged in protection history.

File size difference  - I compressed the exe using `Mpress`.
