### ISSUE TITLE
lines can start with a closing brace

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#26]
```
if false {
    msgbox
} msgbox 3
```

```
if false {
    msgbox
} if var = 5
{
    msgbox 2
}
```

```
var := 5

if false {
    msgbox
} else if var = 5
{
    msgbox 2
}
```

**Comment by mmikeww** [comment]
this could be the same as issue #14 
simply ignore any initial `}` and `else` on a line and then do the conversion and then add them back

**Comment by safetycar** [comment]
Note for future: The test is recommended to use commas, the current conversion does nothing but looks like it does because it is valid v2 as it is.
