### ISSUE TITLE
Extra period in MyOutExt

### ISSUE THREAD

**Issue by kiwichick888** [mmikeww/AHK-v2-script-converter#263]
This may be expected behaviour added recently and not an issue as such. In the last couple of versions at least, the renaming has changed. The new script is being renamed with MyOutExt having a leading period. 

So if:
MyOutExt  := "_newV2.ahk" the new script is renamed ._newV2.ahk
MyOutExt := ".c2v2.ahk" the new script is renamed ..c2v2.ahk.

**Comment by andymbody** [comment]
I have not looked yet, but I would say it's not intentional, and will need to be corrected.

**Comment by Banaanae** [comment]
I can't replicate?
Is it possible that your file extension is 4 characters long? If so see the fix in this [unmerged PR](https://github.com/mmikeww/AHK-v2-script-converter/pull/176/files#diff-d5b7d68af590fa00d231474def956c9434c78763f79d4a69c14cfe581e3f4116R130)

Otherwise please share exactly how you ran the script, (command line arguments, directly ran, etc)

**Comment by fade2gray** [comment]
First time I've tried `v2convertor.ahk`.

V1 file: `test.ah1`
Duplicated as: `test_AHKv1v2_0719161618.ah1` (converted to UTF-8 with BOM ???)
Converted as: `test_newV2.ahk`

No sign of leading periods, but I would personally prefer that the converted file used the `ah2` extension, e.g `test_newV2.ah2`.

**Comment by kiwichick888** [comment]
> I can't replicate? Is it possible that your file extension is 4 characters long? If so see the fix in this [unmerged PR](https://github.com/mmikeww/AHK-v2-script-converter/pull/176/files#diff-d5b7d68af590fa00d231474def956c9434c78763f79d4a69c14cfe581e3f4116R130)
> 
> Otherwise please share exactly how you ran the script, (command line arguments, directly ran, etc)

I'm not using a file extension of my own. The examples I gave are the ones in the v2converter.ahk file.

I run the script, browse to v1 file, select file - that's it. Same as I always do. How else could I run it?

**Comment by andymbody** [comment]
> Edit: The "converted to UTF-8 with BOM" thing, was introduced with the July 15 [e4849c9]

The purpose of this is to ensure that the file viewed by VisualDiff has CRLF line terminators. Some v1 files have LF instead, which causes html errors when VisualDiff tries to read those files. The temp file guarantees CRLF terminators without changing the original v1 file.

**Comment by kiwichick888** [comment]
UPDATE: Well it's a mystery as to what was going on but I've checked again today and the extra period is no longer being added to the converted scripts.

**Comment by Banaanae** [comment]
I have changed some code which should stop future instances of this, if it still happens please reopen this issue
