### ISSUE TITLE
newline preceeding start of cont. section

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#27]
there is already a unit test for this, it is commented out `Continuation_NewlinePreceeding()` here:
https://github.com/mmikeww/AHK-v2-script-converter/blob/master/tests/Tests.ahk#L283

**Comment by safetycar** [comment]
Is this outdated? I couldn't find what it refers to.

**Comment by mmikeww** [comment]
> Is this outdated? I couldn't find what it refers to.

Looks like in the last commit, the test is on line 308

https://github.com/mmikeww/AHK-v2-script-converter/blob/3ce5a779ed40b5ca129cba4275db5114ae3a92cc/tests/Tests.ahk#L308

havent played with this script in a while so not sure. appreciate your updates on the other issues

**Comment by safetycar** [comment]
Ah, it was the double "e" (preceeding) what didn't let me find it. Uncommenting it, it passes.
But the one below it is somehow related and still fails (Continuation_CommandParam).

**Comment by safetycar** [comment]
I saw that the issue on the other tests was not related to this same issue but to #74 
So this one seems solved.
