### ISSUE TITLE
Double quote

### ISSUE THREAD

**Issue by sebastieng-oss** [mmikeww/AHK-v2-script-converter#272]
V1:
MyVar := "FalseOrTrue(""T"")"

V2 (Converted):
MyVar := "FalseOrTrue(""T"")"

V2 (Expected):
MyVar := 'FalseOrTrue("T")'

At the beggining V1 is  
Road := "=HYPERTEXT(""=https://www.mysite.com/Road="")"

**Comment by andymbody** [comment]
@Banaanae... I fixed this and will submit a PR
