### ISSUE TITLE
if var in/contains matchlist

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#29]
v2 changes says `in` and `contains` are reserved for future use

https://autohotkey.com/boards/viewtopic.php?f=37&t=23033

notes from:
https://autohotkey.com/docs/commands/IfIn.htm
> Two consecutive commas results in a single literal comma. For example, the following would produce a single literal comma at the end of string1: `If Var In string1,,,string2`. Similarly, the following list contains only a single item with a literal comma inside it: `If Var In single,,item`. To include a blank item in the list, make the first character a comma as in this example: `If Var In ,string1,string2` (when using the "contains" operator, a blank item will always result in a match since the empty string is found in all strings).

> The comparison is always done alphabetically, not numerically. For example, the string "11" would not match the list item "11.0".

> The "contains" operator is the same as using IfInString/IfNotInString except that multiple search strings are supported (any one of which will cause a match).

> StringCaseSense On can be used to make the comparison case sensitive.

**Comment by mmikeww** [comment]
suggested replacements from AHK docs:

https://www.autohotkey.com/docs/commands/IfIn.htm#Remarks

> The operators "in" and "contains" are not supported in expressions. Instead, use If statements such as `if (Var ~= "iAD)Value1|Value2")` for "in" or `if (Var ~= "i)Value1|Value2")` for "contains" to simulate the behavior of these operators.

**Comment by dmtr99** [comment]
This is implemented
