### ISSUE TITLE
[Suggestion] Commenting out #NoEnv

### ISSUE THREAD

**Issue by vmech** [mmikeww/AHK-v2-script-converter#291]
Why `; REMOVED: #NoEnv` ?
Wouldn't it be better to just replace it with `#Requires Autohotkey 2`

**Comment by Banaanae** [comment]
#125

**Comment by Banaanae** [comment]
I should also not that if this were to be added, it would be added on top of NoEnv, as the Required v2 is not a replacement of NoEnv
