### ISSUE TITLE
Converter fails to handle single-line hotkeys with custom combinations (&)

### ISSUE THREAD

**Issue by Ragnar-F** [mmikeww/AHK-v2-script-converter#306]
V1:
```ahk
F10 & a::Send test
```

V2 (Converted):
```ahk
F10 & a::Send test
```

V2 (Expected):
```ahk
F10 & a::Send("test")
```

When omitting ` & a`, it works as expected. I noticed this issue in the following forum thread: https://www.autohotkey.com/boards/viewtopic.php?p=588753#p588753

**Comment by Banaanae** [comment]
Already fixed in #305
