### ISSUE TITLE
Error:  0x80020101 - Specifically: registerGetter

### ISSUE THREAD

**Issue by waldens** [mmikeww/AHK-v2-script-converter#31]
Win7x64、IE8
After running VisualDiff.exe:
![screenshot](http://onuia4d7l.bkt.clouddn.com/2017_04_13_20170413223636.png)

**Comment by mmikeww** [comment]
The VisualDiff program is just a wrapper around [Aurelain's Exo](https://github.com/Aurelain/Exo/) which allows AHK to interact javascript. 

IE 8 is very old. Is it possible to test on a newer version?

You may need to try running this:

https://gist.github.com/G33kDude/5619463

**Comment by waldens** [comment]
@mmikeww After running FixIE.ahk it still report error, maybe I can try upgrading to IE11 tomorrow.
Also thank you very much for making this migration tool, dispense with a lot of trouble.

**Comment by mmikeww** [comment]
Ok let me know if IE 11 works. Unfortunately, I don't know much about Exo or Mergely, which are used to visually display the results of the conversion.

And you're welcome. As you can see AHK v2 has a lot of changes, and this converter still needs a lot of work! AHK v2 just recently changed `MsgBox` which means a lot of scripts will be broken: 

https://autohotkey.com/boards/viewtopic.php?f=37&t=2120&p=138141#p138141

So if you want to help make this converter better, please feel free to contribute!

**Comment by waldens** [comment]
@mmikeww After upgrade IE11, the diff window can be shown and no error message. Thanks!
I opend another filename issue, #32 🙂
