### ISSUE TITLE
PixelSearch Parameters

### ISSUE THREAD

**Issue by s-sur** [mmikeww/AHK-v2-script-converter#310]
V1:
```ahk
PixelSearch, , , CenterX, 1, CenterX, 1, 0xF3F3F3, 0, Fast
if (Errorlevel == 1)
	{
	ScreenHeightTop := ScreenHeightTop+23
	Height := Height-23
	}
```

V2 (Converted):
```ahk
ErrorLevel := !PixelSearch(, , CenterX, 1, CenterX, 1, 0xF3F3F3) ; V1toV2: Converted colour to RGB format
if (Errorlevel == 1)
	{
	ScreenHeightTop := ScreenHeightTop+23
	Height := Height-23
	}
```

V2 (Expected):
```ahk

```

in V1, you could leave the first 2 parameters empty

**Comment by s-sur** [comment]
Error: "Missing a required parameter"

**Comment by Banaanae** [comment]
Maybe this? couldn't find a way to skip setting a var

```ahk
ErrorLevel := !PixelSearch(&AHKv1v2_TEMP, &AHKv1v2_TEMP, CenterX, 1, CenterX, 1, 0xF3F3F3) ; V1toV2: Converted colour to RGB format
if (Errorlevel == 1)
	{
	ScreenHeightTop := ScreenHeightTop+23
	Height := Height-23
	}
```

**Comment by Banaanae** [comment]
this is also probably an issue with every var to varref conversion
changing `V2VR` param convert is probably best

**Comment by Banaanae** [comment]
But then again, not all out vars are forced
I think when I get feel like it ill begin the tedious task of checking each V2VR and seeing if its mandatory in v2, then do above
