### ISSUE TITLE
CJK character of the file name is garbled - VisualDiff

### ISSUE THREAD

**Issue by waldens** [mmikeww/AHK-v2-script-converter#32]
The filename is `3. 快捷输入.ahk`, cannot be shown correctly with its content also.

![](http://onuia4d7l.bkt.clouddn.com/2017_04_14_20170414041151.png)

**Comment by mmikeww** [comment]
Maybe its some unicode issue. Can you post an example script content that fails ?

**Comment by waldens** [comment]
Seems to have no relationship with the script content. In fact, if I change the file name to English, everything is normal. Similarly, if I leave the content only a simple `msgbox, "ABC"`, but keep the file name is Chinese, like `口.ahk`, still there is gibberish and blank content shown.

The problem may be lie in the processing of file name/paths I guess? so the VisualDiff cannot find the right ahk file.

**Comment by mmikeww** [comment]
Should be good now ^
