### ISSUE TITLE
Four cases that cannot be handled well

### ISSUE THREAD

**Issue by waldens** [mmikeww/AHK-v2-script-converter#33]
This is some problems found when converting my script, the tool does not handle the following four cases well. 

```ahk
;section1
evernoteInsertHTML(str) {
}

evernoteInsertHTML("<div style='margin: 3px 0px; border-top-width: 2px; border-top-style: solid; border-top-color: rgb(116, 98, 67); font-size: 3px'>　</div><span style='font-size: 12px'>&nbsp;</span>")
;style:='margin
      ^

;section2
commands = ("d:\Dropbox\Technical_Backup\ProgramFiles.Trust\Handle 查看文件夹或文件 被哪个程序占用 而无法删除\handle64.exe" %Clipboard% & echo "直接taskkill /PID来结束进程")
runwait, %comspec% /k %commands%
;commands := "("d:\Dropbox\Technical_Backup\ProgramFiles.Trust\Handle åö9ö «ê*`( àÕ d\handle64
                                                                               ^

;section3
method := 1
if( method = 1 )
MsgBox, 111
;if( method := 1 )
            ^

;section4
SendMessage, 0x417, A_Index - 1, pRB, ToolbarWindow32%key%, ahk_class %sTray%   ; TB_GETBUTTON
;                        ^not handle
```
BTW, I decided to return to v1.1, changing my own script is easy, the problem is to cast so many libraries and functions which #included at once, really the big job. Too exhausted. Thank you for your job.

**Comment by mmikeww** [comment]
Thanks

Case1: looks like we would need to check for `=` that are within strings

Case2: unicode conversion, and also have to handle the doublequotes

Case3: I think this may be because there is no space between the `if` and `(` but not sure

Case4: See Issue #17

**Comment by mmikeww** [comment]
Case 3 is fixed

**Comment by mmikeww** [comment]
Case 1 fixed

**Comment by mmikeww** [comment]
Case 2 fixed partially

**Comment by mmikeww** [comment]
Case 2 fixed completely :)
