### ISSUE TITLE
Convert all Commands to Functions?

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#4]
from  
https://autohotkey.com/v2/v2-changes.htm

> All commands can now be called as functions, except for control flow statements such as Return. The translation rules are:
> 
> If the command's first parameter is an output variable and the second parameter is not, it becomes the return value. Otherwise, RunWait and SendMessage return the value of ErrorLevel, and any other commands which set ErrorLevel return 1 on success and 0 on failure. ErrorLevel is still set as usual.
> 
> The remaining output variables are handled like ByRef parameters, except that an exception is thrown if the function is called incorrectly. Passing an empty string is equivalent to omitting the parameter, but any other value (which is not a variable reference) is not allowed.

So:

before:

    WinGetTitle, OutputVar, A

after:

    OutputVar := WinGetTitle("A")

This is only my personal preference, and perhaps an option could be provided to the user

**Comment by mmikeww** [comment]
in v2-a081, the optional comma after the command has been removed, and it is no longer optional, it is no longer allowed at all. So the command must be followed by a space.

**Comment by dmtr99** [comment]
I agree, the function syntax seems more familiar and readable.
