### ISSUE TITLE
if in matchlist

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#50]
@dmtr99 looks like we might want to change the regexes here:

https://github.com/mmikeww/AHK-v2-script-converter/blob/a6aa84fa40a764246f3639b422ba6c2f8223fa01/ConvertFuncs.ahk#L797-L802

see lexikos comments:
https://www.autohotkey.com/boards/viewtopic.php?p=422174#p422174

i think we should use this:
https://www.autohotkey.com/boards/viewtopic.php?p=110700#p110700

**Comment by dmtr99** [comment]
I agree, the changes are now implemented.
