### ISSUE TITLE
Adding mandatory string Type to NumGet with 2 integer parameters

### ISSUE THREAD

**Issue by eugenesvk** [mmikeww/AHK-v2-script-converter#51]
`NumGet(Buffer(1024), A_PtrSize)` raises a runtime error `Invalid parameter(s)` (aside: given that `type` is mandatory, shouldn't this also be an error on script launch? [numget](https://lexikos.github.io/v2/docs/commands/NumGet.htm))
`NumGet(Buffer(1024), A_PtrSize, "UPtr")` doesn't since now we have the mandatory `type` parameter

Converter doesn't change `NumGet(Buffer(1024), A_PtrSize)`, though it does change
`NumGet(Buffer(1024))` to
`NumGet(Buffer(1024), "UPtr")`

Should it also add `"UPtr"` when converting `NumGet(Buffer(1024), A_PtrSize)`

**Comment by dmtr99** [comment]
It could also be a variable with a specific type defined, but I added A_PtrSize to the exceptions, so this case should at least work correctly.
