### ISSUE TITLE
Don't zero out existing variables in DllCalls

### ISSUE THREAD

**Issue by eugenesvk** [mmikeww/AHK-v2-script-converter#54]
```
count:=7
; v1
DllCall("func", "Int",count, "Ptr", &var, "Int*", count)
; v2
DllCall("func", "Int", count, "Ptr", var, "Int*", &count := 0)
```

This breaks the `count` variable that had previous valuable value

**Comment by dmtr99** [comment]
I disabled the := 0 for now, probably this will result in undeclared variables in some scripts, but this is a larger issue.
