### ISSUE TITLE
Missing braces for some codes

### ISSUE THREAD

**Issue by dsl101** [mmikeww/AHK-v2-script-converter#62]
First of all, thank you—this was a fantastic addition to make moving from v1 to v2 tolerable. I used it convert 41 shortcut keys.

I found 2 that just didn't convert properly. Pretty much all of them inserted the braces where needed—e.g.
```ahk
; v1
<^>!C::
	send, {U+00A9}
	Return
```
became
```ahk
<^>!C::
{ ; V1toV2: Added bracket
	Send("{U+00A9}")
	Return
} ; V1toV2: Added bracket in the end
```

But these 2 did not include braces:
```ahk
; v1
!=::
	send, {U+2248}
	Return
```
became
```ahk
!=::
	Send("{U+2248}")
	Return
```
and 
```ahk
; v1
!+=::
	send, {U+00B1}
	Return
```
became
```ahk
!+=::
	Send("{U+00B1}")
	Return
```
which both result in error `Hotkey or hotstring is missing its opening brace.`

**Comment by mmikeww** [comment]
Thanks for the report! Hopefully someone will pick this up to fix

**Comment by SafetyCar** [comment]
There's a part of the regex related to this that I'm not clear on what was trying to guard.
This part `[^;\n\r\{}\[\]\=:]` at lines 3334 and 3337
https://github.com/mmikeww/AHK-v2-script-converter/blob/882e221ff70ce0a5808644e87ce8530bd63db25d/ConvertFuncs.ahk#L3334-L3337
Currently replacing it with a dot doesn't break any test
but it would be nice to know a bit more about it.

**Comment by mmikeww** [comment]
git blame shows that @dmtr99 added this section of code, maybe he can elaborate

But these types of things are exactly the reason why extensive tests for every single corner case is useful... then when we make a change we can see what breaks and what doesnt

**Comment by dmtr99** [comment]
I looked at it and guess this was not necessary. Changed in the master. Tests seems to be fine.
