### ISSUE TITLE
Duplicate function definition (_SendMessage)

### ISSUE THREAD

**Issue by TheArkive** [mmikeww/AHK-v2-script-converter#75]
I tried to run your script from the repo.  I followed the usage instructions 1 and 2.

When I ran the exe, I got the `_SendMessage` duplicate declaration message.

I get the same msg when I run `QuickConvectorV2.ahk` I get the same message.

```
---------------------------
v2converter.ahk
---------------------------
Error at line 2272 in #include file "D:\Media\DL\Various Files\AHK\AHK-v2-script-converter-master\ConvertFuncs.ahk".

Line Text: _SendMessage
Error: This function declaration conflicts with an existing Func.

The program will exit.
---------------------------
OK   
---------------------------

```

**Comment by mmikeww** [comment]
hmm @dmtr99 just made some changes to this, maybe he messed something up

**Comment by safetycar** [comment]
I made a comment yesterday here https://github.com/mmikeww/AHK-v2-script-converter/commit/638700b50f3ac42626d97ef117764a910857c20b
But I don't know if he got a notification or something about it.

**Comment by dmtr99** [comment]
My excuses, I overlooked the function in 1Commands.ahk.

This should be fixed now
