### ISSUE TITLE
Problem registering escaped characters and non escaped characters.

### ISSUE THREAD

**Issue by GameEntity903** [mmikeww/AHK-v2-script-converter#81]
Two instances of this have occurred. Once, it was `% becoming `". Another time it was " " becoming "`" `"".

**Comment by dmtr99** [comment]
Please provide short examples that demonstrates the error, this makes it easier to debug.

**Comment by Banaanae** [comment]
I think the issue is this
V1:
```ahk
MsgBox `% becoming `"
```

V2 (Converted): 
```ahk
MsgBox("`% becoming ``"")
```

V2 (Expected): 
```ahk
MsgBox("`% becoming `"")
```

**Comment by Banaanae** [comment]
Committing fix soon

**Comment by Banaanae** [comment]
Should be fixed now in https://github.com/mmikeww/AHK-v2-script-converter/commit/d5b0b30e47fb78d94efb79a3d407d1d020a7e9d4, if not feel free to reopen
