### ISSUE TITLE
OutputDebug function incorrect conversion

### ISSUE THREAD

**Issue by GameEntity903** [mmikeww/AHK-v2-script-converter#83]
Well, upon inspecting the docs, it turns out that OutputDebug function does not have brackets. Instead of OutputDebug(testvar) it should be OutputDebug testvar.

**Comment by mmikeww** [comment]
Does it not work? I'm pretty sure in v2, all commands can now be written in either function syntax (with parens) or command syntax (without)

**Comment by GameEntity903** [comment]
Well, I don't know. Turns out my computer is not registering v2 as a compiler.

**Comment by GameEntity903** [comment]
Yep, its correct. My bad, I just didn't know what was going on.
