### ISSUE TITLE
Map Initialization

### ISSUE THREAD

**Issue by ronstudy1** [mmikeww/AHK-v2-script-converter#84]
v1 code (which is the first line in some function):
`static map_letter_digit:={q:7,w:8,e:9,a:4,s:5,d:6,z:1,x:2,c:3,f:0,g:0," ":0}`
actual converted v2 code:
`static map_letter_digit:=map("q", 7, "w", 8, "e", 9, "a", 4, "s", 5, "d", 6, "z", 1, "x", 2, "c", 3, "f", 0, "g", 0," ":0}`
expected converted v2 code:
`static map_letter_digit:=map("q", 7, "w", 8, "e", 9, "a", 4, "s", 5, "d", 6, "z", 1, "x", 2, "c", 3, "f", 0, "g", 0," ", 0)`

----
might be a difference bug, but here is another example of failing Dictionary Initialization:
v1 code:
`static map_open_close_chars:={"{":"}", "[":"]", "(":")", "<":">"}`
actual converted v2 code:
`static map_open_close_chars:=map("{", ")", "[":"]", "(":")", "<":">"}`
expected converted v2 code:
`static map_open_close_chars:=map("{", ")", "[", "]", "(", ")", "<", ">")`

**Comment by dmtr99** [comment]
Can you try to use the latest conversion?
I get:
static map_letter_digit:={q:7,w:8,e:9,a:4,s:5,d:6,z:1,x:2,c:3,f:0,g:0," ":0}

It does not seems to convert it into a map anymore, as it is an object...

**Comment by ronstudy1** [comment]
I apologize for not including the complete context of the code. This issue only occurs when there is a loop that iterates over the map and is not consistently replicated.

original code:
```
^a::
	myMap:={q:7,w:8,e:9,a:4,s:5,d:6,z:1,x:2,c:3,f:0,g:0," ":0}
	for key, value in myMap {
		msgbox %key%|%value%
	}
return

^q::ExitApp
```

actual converted code:
```
^a::
{ ; V1toV2: Added bracket
	myMap:=map("q", 7, "w", 8, "e", 9, "a", 4, "s", 5, "d", 6, "z", 1, "x", 2, "c", 3, "f", 0, "g", 0," ":0}
	for key, value in myMap {
		MsgBox(key "|" value)
	}
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

^q::ExitApp()

```

expected converted code (at the "myMap:=" line, ")" should be used instead of "}" and "," instead of ":"):
```
^a::
{ ; V1toV2: Added bracket
	myMap:=map("q", 7, "w", 8, "e", 9, "a", 4, "s", 5, "d", 6, "z", 1, "x", 2, "c", 3, "f", 0, "g", 0," ", 0)
	for key, value in myMap {
		MsgBox(key "|" value)
	}
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

^q::ExitApp()

```

---------------------

it might be a different problem but the following code is also not converted correctly:
original code:
```
^a::
	myMap:={" ":0}
	for key, value in myMap {
		msgbox %key%|%value%
	}
return

^q::ExitApp
```

actual converted code:
```
^a::
{ ; V1toV2: Added bracket
	myMap:={" ":0}
	for key, value in myMap {
		MsgBox(key "|" value)
	}
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

^q::ExitApp()

```

however. v2 doesn't seem to support a space key on object initalization, so "map" should probably be used in such cases
so the expected converted code:
```
^a::
{ ; V1toV2: Added bracket
	myMap:=map(" ", 0)
	for key, value in myMap {
		MsgBox(key "|" value)
	}
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

^q::ExitApp()

```

**Comment by dmtr99** [comment]
This is now fixed.

I am wondering if it wouldn`t be better to add a setting on how to handle v1 objects, convert them to maps or let them be objects...
