### ISSUE TITLE
Function with Default Param Value

### ISSUE THREAD

**Issue by ronstudy1** [mmikeww/AHK-v2-script-converter#85]
v1 code (definition of function):
`my_function(txt, more_params=""){`
actual converted v2 code (same):
`my_function(txt, more_params=""){`
expected converted v2 code:
`my_function(txt, more_params:=""){`

i'm aware that this syntax ("=" instead of ":=") might not be officially supported also in v1. yet, it worked in v1 without errors

**Comment by dmtr99** [comment]
There is an "if" in not**IF**ication.... 😁

I updated the conversion, this should be fixed now.
