### ISSUE TITLE
Brackets {} with condition hotkey

### ISSUE THREAD

**Issue by xIrbis** [mmikeww/AHK-v2-script-converter#88]
**V1**
#If WinActive("ahk_exe Notepad.exe")
F1::
MsgBox Notepad is active!
Return
#If

**v2** (Error: Invalid usage)
#HotIf WinActive("ahk_exe Notepad.exe")
F1::
{ ; V1toV2: Added bracket
MsgBox("Notepad is active!")
Return
#HotIf
} ; V1toV2: Added bracket in the end

**v2** (manually edited)
#HotIf WinActive("ahk_exe Notepad.exe")
F1::
{ ; V1toV2: Added bracket
MsgBox("Notepad is active!")
Return
} ; V1toV2: Added bracket in the end
#HotIf

**Comment by dmtr99** [comment]
Updated ConvertFuncs.ahk
Fixed
