### ISSUE TITLE
Initialization of empty variables using = being converted to :=

### ISSUE THREAD

**Issue by allchannelson** [mmikeww/AHK-v2-script-converter#89]
I use `output =` as initialization but it gets converted to `output :=` and this is incorrect syntax.

Correct syntax would be `output := ""` only for the special case where `=` is followed by nothing in V1 syntax.

**Comment by mmikeww** [comment]
post full example code and conversion code

**Comment by dmtr99** [comment]
I also could not repeat this...
I did found another error
var := should become var := ""
this is fixed now
