### ISSUE TITLE
General formating

### ISSUE THREAD

**Issue by drposts** [mmikeww/AHK-v2-script-converter#93]
Mike,
Thanks for these great scripts.  I hope to help with some of the conversion and tests soon.  

As you know, I looked at v2converter.  It provided me with a source to batch process v1 files.

Thank you for referring me to QuickConverterV2.ahk.  

When working with new software, I find that spending a few minutes organizing a program can save me a lot of time.  It also gives me an opportunity to look at the basic structures.

Attached is a copy of my first run through on QuickConverterV2.ahk.  I did very little to the code.  I added:
    #Requires AutoHotkey >=2.0 - <2.1
-and-
     Esc::     ;Exit application - Using either <Esc> Hotkey or Goto("MyExit")
     {
     MyExit:
       ExitApp
       Return
     }
The latter provides an external exit for wayward behavior and a way to quickly remove the program from the background.

Take a look at what toggling all folds does (in SciTE4AutoHotkey: <Alt><v> + <a>) 

[QuickConvertorV2.ahk.txt](https://github.com/mmikeww/AHK-v2-script-converter/files/10844668/QuickConvertorV2.ahk.txt)

**Comment by dmtr99** [comment]
Updated QuickConvertorV2
