### ISSUE TITLE
Unstable close

### ISSUE THREAD

**Issue by drposts** [mmikeww/AHK-v2-script-converter#95]
Should be able to force the program to close via HotKey.

Esc::
{
  MyGui.Destroy
  ExitApp
)

Results in error:

![ESC_HOTKEY_Error_1_Screenshot 2023-02-28 135356](https://user-images.githubusercontent.com/36614589/221951794-a9b0f42f-693d-4e90-8ed9-04f3ec67ccd6.png)

The commented out line 694
;MyGui.OnEvent("Escape", (*) => ExitApp())
If uncommentedd out results in the same unstable closure so I assume you are already aware of the issue.  It appears to be due to an internal loop since it does not appear to be due to an issue with the custom scintilla controls.

The following code works:

[test.ahk.TXT](https://github.com/mmikeww/AHK-v2-script-converter/files/10886730/test.ahk.TXT)

**Comment by dmtr99** [comment]
Updated, Escape seems to work now to exit the script
