### ISSUE TITLE
VisualDiff.ahk 

### ISSUE THREAD

**Issue by LAPIII** [mmikeww/AHK-v2-script-converter#99]
I usually get this error:

![Script_Error 25_03_23 09⦂54⦂40⦂732 PM](https://user-images.githubusercontent.com/7947363/227751376-db4da05f-e8fa-4088-a1e4-696f2bf54487.jpg)

What does it mean?

**Comment by mmikeww** [comment]
It could mean that the mergely.js library needs to be updated. I'd just ignore it. Does it still display the diff between the v1 and v2 conversion?

**Comment by LAPIII** [comment]
yes
